# Generated by Django 5.2.2 on 2025-06-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='posts',
            table='blog_posts',
        ),
    ]
